### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET localhost:8080/api/pois
Authorization: ac458bf8-3b5d-47fa-a731-89cca4d856d2
###
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "test",
  "password": "1234",
  "email": "m@hs-kl.de",
  "firstname": "Moha",
  "lastname": "Aloha",
  "street": "Hauptstraße",
  "streetNr": "1",
  "zip": "66482",
  "city": "Zweibrücken"
}

###
POST http://localhost:8080/api/ratings
Authorization: 688f7eb0-2ec6-4014-9222-ae8f1a2eb9d0
Content-Type: application/json

{
  "poiId": 933057175,
  "grade": 4,
  "txt": "Great food!",
  "imageId": null
}